# version: '3.8'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080  # URL для обращения к backend

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./backend/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://db:5432/your_database
  #     - DATABASE_USER=your_user
  #     - DATABASE_PASSWORD=your_password


  backend-api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        PROJECT: backend-api
    # command: sbt "backend-api/Compile / run"
    ports:
      - "8081:8080"
  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: ./backend/Dockerfile
  #     args:
  #       PROJECT: backend-api
  #   ports:
  #     - "8081:8080"  # Подключение к backend-api на порту 8081
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=jdbc:postgresql://db:5432/your_database
    #   - DATABASE_USER=your_user
    #   - DATABASE_PASSWORD=your_password

# version: '3.8'

# services:
  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #     args:
  #       PROJECT: backend
  #   ports:
  #     - "8081:8080"  # Подключение к backend-api на порту 8081





#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: your_user
#       POSTGRES_PASSWORD: your_password
#       POSTGRES_DB: your_database
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   db-data:
